//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSASA.Web.EmployeesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SSASA.Web.EmployeesService.Employee))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPIField;
        
        private System.DateTime BirthDateField;
        
        private char GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NITField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FullNames {
            get {
                return this.FullNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNamesField, value) != true)) {
                    this.FullNamesField = value;
                    this.RaisePropertyChanged("FullNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DPI {
            get {
                return this.DPIField;
            }
            set {
                if ((object.ReferenceEquals(this.DPIField, value) != true)) {
                    this.DPIField = value;
                    this.RaisePropertyChanged("DPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public char Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NIT {
            get {
                return this.NITField;
            }
            set {
                if ((object.ReferenceEquals(this.NITField, value) != true)) {
                    this.NITField = value;
                    this.RaisePropertyChanged("NIT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : SSASA.Web.EmployeesService.Person {
        
        private int EmployeeIdField;
        
        private System.DateTime HireDateField;
        
        private bool IsActiveField;
        
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenureField;
        
        private int AgeField;
        
        private bool DepartmentIsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime HireDate {
            get {
                return this.HireDateField;
            }
            set {
                if ((this.HireDateField.Equals(value) != true)) {
                    this.HireDateField = value;
                    this.RaisePropertyChanged("HireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tenure {
            get {
                return this.TenureField;
            }
            set {
                if ((object.ReferenceEquals(this.TenureField, value) != true)) {
                    this.TenureField = value;
                    this.RaisePropertyChanged("Tenure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool DepartmentIsActive {
            get {
                return this.DepartmentIsActiveField;
            }
            set {
                if ((this.DepartmentIsActiveField.Equals(value) != true)) {
                    this.DepartmentIsActiveField = value;
                    this.RaisePropertyChanged("DepartmentIsActive");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesService.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SSASA.Web.EmployeesService.HelloWorldResponse HelloWorld(SSASA.Web.EmployeesService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.HelloWorldResponse> HelloWorldAsync(SSASA.Web.EmployeesService.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento emp del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEmployee", ReplyAction="*")]
        SSASA.Web.EmployeesService.SaveEmployeeResponse SaveEmployee(SSASA.Web.EmployeesService.SaveEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.SaveEmployeeResponse> SaveEmployeeAsync(SSASA.Web.EmployeesService.SaveEmployeeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllEmployeesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        SSASA.Web.EmployeesService.GetAllEmployeesResponse GetAllEmployees(SSASA.Web.EmployeesService.GetAllEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetAllEmployeesResponse> GetAllEmployeesAsync(SSASA.Web.EmployeesService.GetAllEmployeesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dept del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDepartment", ReplyAction="*")]
        SSASA.Web.EmployeesService.SaveDepartmentResponse SaveDepartment(SSASA.Web.EmployeesService.SaveDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.SaveDepartmentResponse> SaveDepartmentAsync(SSASA.Web.EmployeesService.SaveDepartmentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetEmployeeByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeById", ReplyAction="*")]
        SSASA.Web.EmployeesService.GetEmployeeByIdResponse GetEmployeeById(SSASA.Web.EmployeesService.GetEmployeeByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeById", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetEmployeeByIdResponse> GetEmployeeByIdAsync(SSASA.Web.EmployeesService.GetEmployeeByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        bool DeleteEmployee(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(int employeeId);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllDepartmentsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDepartments", ReplyAction="*")]
        SSASA.Web.EmployeesService.GetAllDepartmentsResponse GetAllDepartments(SSASA.Web.EmployeesService.GetAllDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetAllDepartmentsResponse> GetAllDepartmentsAsync(SSASA.Web.EmployeesService.GetAllDepartmentsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDepartmentByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartmentById", ReplyAction="*")]
        SSASA.Web.EmployeesService.GetDepartmentByIdResponse GetDepartmentById(SSASA.Web.EmployeesService.GetDepartmentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartmentById", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetDepartmentByIdResponse> GetDepartmentByIdAsync(SSASA.Web.EmployeesService.GetDepartmentByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetEmployeeReportResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeReport", ReplyAction="*")]
        SSASA.Web.EmployeesService.GetEmployeeReportResponse GetEmployeeReport(SSASA.Web.EmployeesService.GetEmployeeReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeReport", ReplyAction="*")]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetEmployeeReportResponse> GetEmployeeReportAsync(SSASA.Web.EmployeesService.GetEmployeeReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SSASA.Web.EmployeesService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SSASA.Web.EmployeesService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveEmployee", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.SaveEmployeeRequestBody Body;
        
        public SaveEmployeeRequest() {
        }
        
        public SaveEmployeeRequest(SSASA.Web.EmployeesService.SaveEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Employee emp;
        
        public SaveEmployeeRequestBody() {
        }
        
        public SaveEmployeeRequestBody(SSASA.Web.EmployeesService.Employee emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.SaveEmployeeResponseBody Body;
        
        public SaveEmployeeResponse() {
        }
        
        public SaveEmployeeResponse(SSASA.Web.EmployeesService.SaveEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveEmployeeResult;
        
        public SaveEmployeeResponseBody() {
        }
        
        public SaveEmployeeResponseBody(bool SaveEmployeeResult) {
            this.SaveEmployeeResult = SaveEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetAllEmployeesRequestBody Body;
        
        public GetAllEmployeesRequest() {
        }
        
        public GetAllEmployeesRequest(SSASA.Web.EmployeesService.GetAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeesRequestBody {
        
        public GetAllEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetAllEmployeesResponseBody Body;
        
        public GetAllEmployeesResponse() {
        }
        
        public GetAllEmployeesResponse(SSASA.Web.EmployeesService.GetAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Employee[] GetAllEmployeesResult;
        
        public GetAllEmployeesResponseBody() {
        }
        
        public GetAllEmployeesResponseBody(SSASA.Web.EmployeesService.Employee[] GetAllEmployeesResult) {
            this.GetAllEmployeesResult = GetAllEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDepartment", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.SaveDepartmentRequestBody Body;
        
        public SaveDepartmentRequest() {
        }
        
        public SaveDepartmentRequest(SSASA.Web.EmployeesService.SaveDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Department dept;
        
        public SaveDepartmentRequestBody() {
        }
        
        public SaveDepartmentRequestBody(SSASA.Web.EmployeesService.Department dept) {
            this.dept = dept;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.SaveDepartmentResponseBody Body;
        
        public SaveDepartmentResponse() {
        }
        
        public SaveDepartmentResponse(SSASA.Web.EmployeesService.SaveDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveDepartmentResult;
        
        public SaveDepartmentResponseBody() {
        }
        
        public SaveDepartmentResponseBody(bool SaveDepartmentResult) {
            this.SaveDepartmentResult = SaveDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeById", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetEmployeeByIdRequestBody Body;
        
        public GetEmployeeByIdRequest() {
        }
        
        public GetEmployeeByIdRequest(SSASA.Web.EmployeesService.GetEmployeeByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetEmployeeByIdRequestBody() {
        }
        
        public GetEmployeeByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetEmployeeByIdResponseBody Body;
        
        public GetEmployeeByIdResponse() {
        }
        
        public GetEmployeeByIdResponse(SSASA.Web.EmployeesService.GetEmployeeByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Employee GetEmployeeByIdResult;
        
        public GetEmployeeByIdResponseBody() {
        }
        
        public GetEmployeeByIdResponseBody(SSASA.Web.EmployeesService.Employee GetEmployeeByIdResult) {
            this.GetEmployeeByIdResult = GetEmployeeByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDepartments", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetAllDepartmentsRequestBody Body;
        
        public GetAllDepartmentsRequest() {
        }
        
        public GetAllDepartmentsRequest(SSASA.Web.EmployeesService.GetAllDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDepartmentsRequestBody {
        
        public GetAllDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDepartmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetAllDepartmentsResponseBody Body;
        
        public GetAllDepartmentsResponse() {
        }
        
        public GetAllDepartmentsResponse(SSASA.Web.EmployeesService.GetAllDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Department[] GetAllDepartmentsResult;
        
        public GetAllDepartmentsResponseBody() {
        }
        
        public GetAllDepartmentsResponseBody(SSASA.Web.EmployeesService.Department[] GetAllDepartmentsResult) {
            this.GetAllDepartmentsResult = GetAllDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentById", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetDepartmentByIdRequestBody Body;
        
        public GetDepartmentByIdRequest() {
        }
        
        public GetDepartmentByIdRequest(SSASA.Web.EmployeesService.GetDepartmentByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int departmentId;
        
        public GetDepartmentByIdRequestBody() {
        }
        
        public GetDepartmentByIdRequestBody(int departmentId) {
            this.departmentId = departmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetDepartmentByIdResponseBody Body;
        
        public GetDepartmentByIdResponse() {
        }
        
        public GetDepartmentByIdResponse(SSASA.Web.EmployeesService.GetDepartmentByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Department GetDepartmentByIdResult;
        
        public GetDepartmentByIdResponseBody() {
        }
        
        public GetDepartmentByIdResponseBody(SSASA.Web.EmployeesService.Department GetDepartmentByIdResult) {
            this.GetDepartmentByIdResult = GetDepartmentByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeReport", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetEmployeeReportRequestBody Body;
        
        public GetEmployeeReportRequest() {
        }
        
        public GetEmployeeReportRequest(SSASA.Web.EmployeesService.GetEmployeeReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> departmentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<bool> status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> endDate;
        
        public GetEmployeeReportRequestBody() {
        }
        
        public GetEmployeeReportRequestBody(System.Nullable<int> departmentId, System.Nullable<bool> status, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            this.departmentId = departmentId;
            this.status = status;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public SSASA.Web.EmployeesService.GetEmployeeReportResponseBody Body;
        
        public GetEmployeeReportResponse() {
        }
        
        public GetEmployeeReportResponse(SSASA.Web.EmployeesService.GetEmployeeReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SSASA.Web.EmployeesService.Employee[] GetEmployeeReportResult;
        
        public GetEmployeeReportResponseBody() {
        }
        
        public GetEmployeeReportResponseBody(SSASA.Web.EmployeesService.Employee[] GetEmployeeReportResult) {
            this.GetEmployeeReportResult = GetEmployeeReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : SSASA.Web.EmployeesService.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<SSASA.Web.EmployeesService.EmployeeServiceSoap>, SSASA.Web.EmployeesService.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.HelloWorldResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.HelloWorld(SSASA.Web.EmployeesService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SSASA.Web.EmployeesService.HelloWorldRequest inValue = new SSASA.Web.EmployeesService.HelloWorldRequest();
            inValue.Body = new SSASA.Web.EmployeesService.HelloWorldRequestBody();
            SSASA.Web.EmployeesService.HelloWorldResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.HelloWorldResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.HelloWorldAsync(SSASA.Web.EmployeesService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.HelloWorldResponse> HelloWorldAsync() {
            SSASA.Web.EmployeesService.HelloWorldRequest inValue = new SSASA.Web.EmployeesService.HelloWorldRequest();
            inValue.Body = new SSASA.Web.EmployeesService.HelloWorldRequestBody();
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.SaveEmployeeResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.SaveEmployee(SSASA.Web.EmployeesService.SaveEmployeeRequest request) {
            return base.Channel.SaveEmployee(request);
        }
        
        public bool SaveEmployee(SSASA.Web.EmployeesService.Employee emp) {
            SSASA.Web.EmployeesService.SaveEmployeeRequest inValue = new SSASA.Web.EmployeesService.SaveEmployeeRequest();
            inValue.Body = new SSASA.Web.EmployeesService.SaveEmployeeRequestBody();
            inValue.Body.emp = emp;
            SSASA.Web.EmployeesService.SaveEmployeeResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).SaveEmployee(inValue);
            return retVal.Body.SaveEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.SaveEmployeeResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.SaveEmployeeAsync(SSASA.Web.EmployeesService.SaveEmployeeRequest request) {
            return base.Channel.SaveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.SaveEmployeeResponse> SaveEmployeeAsync(SSASA.Web.EmployeesService.Employee emp) {
            SSASA.Web.EmployeesService.SaveEmployeeRequest inValue = new SSASA.Web.EmployeesService.SaveEmployeeRequest();
            inValue.Body = new SSASA.Web.EmployeesService.SaveEmployeeRequestBody();
            inValue.Body.emp = emp;
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).SaveEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.GetAllEmployeesResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.GetAllEmployees(SSASA.Web.EmployeesService.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployees(request);
        }
        
        public SSASA.Web.EmployeesService.Employee[] GetAllEmployees() {
            SSASA.Web.EmployeesService.GetAllEmployeesRequest inValue = new SSASA.Web.EmployeesService.GetAllEmployeesRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetAllEmployeesRequestBody();
            SSASA.Web.EmployeesService.GetAllEmployeesResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetAllEmployees(inValue);
            return retVal.Body.GetAllEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetAllEmployeesResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.GetAllEmployeesAsync(SSASA.Web.EmployeesService.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetAllEmployeesResponse> GetAllEmployeesAsync() {
            SSASA.Web.EmployeesService.GetAllEmployeesRequest inValue = new SSASA.Web.EmployeesService.GetAllEmployeesRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetAllEmployeesRequestBody();
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetAllEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.SaveDepartmentResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.SaveDepartment(SSASA.Web.EmployeesService.SaveDepartmentRequest request) {
            return base.Channel.SaveDepartment(request);
        }
        
        public bool SaveDepartment(SSASA.Web.EmployeesService.Department dept) {
            SSASA.Web.EmployeesService.SaveDepartmentRequest inValue = new SSASA.Web.EmployeesService.SaveDepartmentRequest();
            inValue.Body = new SSASA.Web.EmployeesService.SaveDepartmentRequestBody();
            inValue.Body.dept = dept;
            SSASA.Web.EmployeesService.SaveDepartmentResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).SaveDepartment(inValue);
            return retVal.Body.SaveDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.SaveDepartmentResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.SaveDepartmentAsync(SSASA.Web.EmployeesService.SaveDepartmentRequest request) {
            return base.Channel.SaveDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.SaveDepartmentResponse> SaveDepartmentAsync(SSASA.Web.EmployeesService.Department dept) {
            SSASA.Web.EmployeesService.SaveDepartmentRequest inValue = new SSASA.Web.EmployeesService.SaveDepartmentRequest();
            inValue.Body = new SSASA.Web.EmployeesService.SaveDepartmentRequestBody();
            inValue.Body.dept = dept;
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).SaveDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.GetEmployeeByIdResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.GetEmployeeById(SSASA.Web.EmployeesService.GetEmployeeByIdRequest request) {
            return base.Channel.GetEmployeeById(request);
        }
        
        public SSASA.Web.EmployeesService.Employee GetEmployeeById(int id) {
            SSASA.Web.EmployeesService.GetEmployeeByIdRequest inValue = new SSASA.Web.EmployeesService.GetEmployeeByIdRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetEmployeeByIdRequestBody();
            inValue.Body.id = id;
            SSASA.Web.EmployeesService.GetEmployeeByIdResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetEmployeeById(inValue);
            return retVal.Body.GetEmployeeByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetEmployeeByIdResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.GetEmployeeByIdAsync(SSASA.Web.EmployeesService.GetEmployeeByIdRequest request) {
            return base.Channel.GetEmployeeByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetEmployeeByIdResponse> GetEmployeeByIdAsync(int id) {
            SSASA.Web.EmployeesService.GetEmployeeByIdRequest inValue = new SSASA.Web.EmployeesService.GetEmployeeByIdRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetEmployeeByIdRequestBody();
            inValue.Body.id = id;
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetEmployeeByIdAsync(inValue);
        }
        
        public bool DeleteEmployee(int employeeId) {
            return base.Channel.DeleteEmployee(employeeId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(int employeeId) {
            return base.Channel.DeleteEmployeeAsync(employeeId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.GetAllDepartmentsResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.GetAllDepartments(SSASA.Web.EmployeesService.GetAllDepartmentsRequest request) {
            return base.Channel.GetAllDepartments(request);
        }
        
        public SSASA.Web.EmployeesService.Department[] GetAllDepartments() {
            SSASA.Web.EmployeesService.GetAllDepartmentsRequest inValue = new SSASA.Web.EmployeesService.GetAllDepartmentsRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetAllDepartmentsRequestBody();
            SSASA.Web.EmployeesService.GetAllDepartmentsResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetAllDepartments(inValue);
            return retVal.Body.GetAllDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetAllDepartmentsResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.GetAllDepartmentsAsync(SSASA.Web.EmployeesService.GetAllDepartmentsRequest request) {
            return base.Channel.GetAllDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetAllDepartmentsResponse> GetAllDepartmentsAsync() {
            SSASA.Web.EmployeesService.GetAllDepartmentsRequest inValue = new SSASA.Web.EmployeesService.GetAllDepartmentsRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetAllDepartmentsRequestBody();
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetAllDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.GetDepartmentByIdResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.GetDepartmentById(SSASA.Web.EmployeesService.GetDepartmentByIdRequest request) {
            return base.Channel.GetDepartmentById(request);
        }
        
        public SSASA.Web.EmployeesService.Department GetDepartmentById(int departmentId) {
            SSASA.Web.EmployeesService.GetDepartmentByIdRequest inValue = new SSASA.Web.EmployeesService.GetDepartmentByIdRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetDepartmentByIdRequestBody();
            inValue.Body.departmentId = departmentId;
            SSASA.Web.EmployeesService.GetDepartmentByIdResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetDepartmentById(inValue);
            return retVal.Body.GetDepartmentByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetDepartmentByIdResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.GetDepartmentByIdAsync(SSASA.Web.EmployeesService.GetDepartmentByIdRequest request) {
            return base.Channel.GetDepartmentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetDepartmentByIdResponse> GetDepartmentByIdAsync(int departmentId) {
            SSASA.Web.EmployeesService.GetDepartmentByIdRequest inValue = new SSASA.Web.EmployeesService.GetDepartmentByIdRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetDepartmentByIdRequestBody();
            inValue.Body.departmentId = departmentId;
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetDepartmentByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSASA.Web.EmployeesService.GetEmployeeReportResponse SSASA.Web.EmployeesService.EmployeeServiceSoap.GetEmployeeReport(SSASA.Web.EmployeesService.GetEmployeeReportRequest request) {
            return base.Channel.GetEmployeeReport(request);
        }
        
        public SSASA.Web.EmployeesService.Employee[] GetEmployeeReport(System.Nullable<int> departmentId, System.Nullable<bool> status, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            SSASA.Web.EmployeesService.GetEmployeeReportRequest inValue = new SSASA.Web.EmployeesService.GetEmployeeReportRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetEmployeeReportRequestBody();
            inValue.Body.departmentId = departmentId;
            inValue.Body.status = status;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            SSASA.Web.EmployeesService.GetEmployeeReportResponse retVal = ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetEmployeeReport(inValue);
            return retVal.Body.GetEmployeeReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetEmployeeReportResponse> SSASA.Web.EmployeesService.EmployeeServiceSoap.GetEmployeeReportAsync(SSASA.Web.EmployeesService.GetEmployeeReportRequest request) {
            return base.Channel.GetEmployeeReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSASA.Web.EmployeesService.GetEmployeeReportResponse> GetEmployeeReportAsync(System.Nullable<int> departmentId, System.Nullable<bool> status, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            SSASA.Web.EmployeesService.GetEmployeeReportRequest inValue = new SSASA.Web.EmployeesService.GetEmployeeReportRequest();
            inValue.Body = new SSASA.Web.EmployeesService.GetEmployeeReportRequestBody();
            inValue.Body.departmentId = departmentId;
            inValue.Body.status = status;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((SSASA.Web.EmployeesService.EmployeeServiceSoap)(this)).GetEmployeeReportAsync(inValue);
        }
    }
}
